version: "3"

services: 
    web:
        container_name: library
        restart: always
        build: .
        ports:
            - "4000:3000"
        links:
            - mongo
            - cache
    mongo:
        container_name: mongodb
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=""
            - MONGO_INITDB_DATABASE=library
        ports:
            - "27017:27017"
    cache:
        image: redis
        restart: always
        ports:
            - "6379:6379"
    
        